server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      database: bank-account
      username: root
      password: example
      authentication-database: admin